[project]
name = "openseeface"
version = "1.20.4"
description = ""
authors = ["emilianavt"]
license = "BSD-2-Clause"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "onnxruntime>=1.22.0",
    "opencv-python>=4.11.0.86",
    "pillow>=11.2.1",
]
